### ISSUE TITLE
QT Creater 5.10 MingW Version can not compile

### ISSUE THREAD

**Issue by QTiLover** [czyt1988/sa#1]
QT Creater 5.10 MingW Version can not compile
With Message bellow:
:-1: error: cannot find -lsignALib
:-1: error: cannot find -lsignAChart
collect2.exe:-1: error: error: ld returned 1 exit status

Pls Check and fix this issue Thks

**Comment by czyt1988** [comment]
修正了这个错误，主要是用Qt Creator的影子构建（shadow build）导致路径不一致，后来把pro文件的相对路径都加上$${PWD}解决影子构建时的路径不一致问题，具体构建过程请看：https://github.com/czyt1988/sa/blob/master/build.md

---------This is the Chinese English segmentation line-------------------------------

This bug was fixed mainly due to inconsistent paths caused by Qt Creator's shadow build. In this modification, I added the relative path to the pro file with $${PWD} to resolve the path inconsistency during shadow build. Problems, specific build tutorials please see: https://github.com/czyt1988/sa/blob/master/build.md

**Comment by xunge** [comment]
你好，我按照 [https://github.com/czyt1988/sa/blob/master/build.md](https://github.com/czyt1988/sa/blob/master/build.md) 构建后报了相同的错误
- error: cannot find -lqwtd
- error: cannot find -lsignALib
- error: cannot find -lsignAChart

使用Qt Creator，Qt 5.9.8 MinGW 32bit，win10
请问我应该如何修改才能正确构建？谢谢~
